[package]
name = "regrs"
version = "0.1.0"
edition = "2021"

[lib]
name = "regrs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.20.2", features = ["extension-module"] }
ndarray-linalg = { version = "0.16.0", features = ["intel-mkl-static"] }
numpy = "0.20.0"
rayon = "1.8"